const packagesData = [
  {
    id: 'imperial-europe',
    title: 'Imperial Europe & Alps Explorer',
    category: 'Exploration',
    rating: 5.0,
    reviewCount: 34,
    quote: "From Roman Legends to Alpine Wonders — Europe's Greatest Highlights",
    quoteAuthor: "Eutours",
    quoteMonth: "May",
    duration: 13,
    countries: ['Italy', 'Austria', 'Germany'],
    destinations: 'Rome, Naples, Florence, Pisa, Milan, Venice, Salzburg, Munich',
    ageRange: 'All Ages Welcome',
    operatedIn: 'English',
    operator: 'Eutours Premium',
    discount: 'Special Offer',
    roomType: 'Price based on Shared/Private Room',
    images: ['/images/Italy.webp', '/images/Austria.webp', '/images/Germany.webp', '/images/Switzerland.webp', '/images/France.webp'],
    itinerary: [
      { day: 1, title: 'Rome & Naples', desc: 'Colosseum • Vatican Museums • Sistine Chapel • St. Peter\'s Basilica • Trevi Fountain • Pantheon • Piazza Navona • Pompeii • Mount Vesuvius' },
      { day: 2, title: 'Rome & Naples', desc: 'Colosseum • Vatican Museums • Sistine Chapel • St. Peter\'s Basilica • Trevi Fountain • Pantheon • Piazza Navona • Pompeii • Mount Vesuvius' },
      { day: 3, title: 'Rome & Naples', desc: 'Colosseum • Vatican Museums • Sistine Chapel • St. Peter\'s Basilica • Trevi Fountain • Pantheon • Piazza Navona • Pompeii • Mount Vesuvius' },
      { day: 4, title: 'Florence & Tuscany', desc: 'Florence Duomo • Ponte Vecchio • Piazza Della Signoria • Tuscan Vineyard & Wine Experience' },
      { day: 5, title: 'Pisa & Supercars', desc: 'Leaning Tower of Pisa • Optional Ferrari/Lamborghini Factory, Museum & Self-Drive Experience on availability' },
      { day: 6, title: 'Milan', desc: 'Duomo di Milano • Leonardo da Vinci\'s The Last Supper • Shopping & Leisure' },
      { day: 7, title: 'Verona & Venice', desc: 'Juliet\'s House • St. Anthony\'s Basilica • Gondola Ride • Murano Glass Workshops' },
      { day: 8, title: 'Verona & Venice', desc: 'Juliet\'s House • St. Anthony\'s Basilica • Gondola Ride • Murano Glass Workshops' },
      { day: 9, title: 'Austrian Alps', desc: 'Salzburg • Boat Cruise • Mozart\'s birthplace • Spectacular Alpine Landscapes' },
      { day: 10, title: 'Austrian Alps', desc: 'Salzburg • Boat Cruise • Mozart\'s birthplace • Spectacular Alpine Landscapes' },
      { day: 11, title: 'Austrian Alps', desc: 'Salzburg • Boat Cruise • Mozart\'s birthplace • Spectacular Alpine Landscapes' },
      { day: 12, title: 'Munich', desc: 'BMW facility • Marienplatz • Viktualienmarkt • Munich Airport Drop-Off' },
      { day: 13, title: 'Munich', desc: 'BMW facility • Marienplatz • Viktualienmarkt • Munich Airport Drop-Off' }
    ]
  },
  {
    id: 'grand-marian',
    title: 'The Grand Marian & Saints Pilgrimage',
    category: 'Pilgrimage',
    rating: 4.9,
    reviewCount: 42,
    quote: "A Sacred Journey of Faith, Prayer & Grace Across Europe's Most Revered Catholic Shrines",
    quoteAuthor: "Eutours",
    quoteMonth: "June",
    duration: 15,
    countries: ['Italy', 'France', 'Spain', 'Portugal'],
    destinations: 'Rome, Assisi, Lanciano, San Giovanni Rotondo, Padua, Lourdes, Barcelona, Zaragoza, Fatima',
    ageRange: 'All Ages Welcome',
    operatedIn: 'English',
    operator: 'Eutours Premium',
    discount: 'Special Offer',
    roomType: 'Price based on Shared/Private Room',
    images: ['/images/Italy.webp', '/images/France.webp', '/images/Spain.webp', '/images/Portugal.webp', '/images/Austria.webp'],
    itinerary: [
      { day: 1, title: 'Italy – In the Footsteps of the Saints', desc: 'Rome • Vatican City • Assisi • Lanciano • San Giovanni Rotondo • Padua. Vatican Museums & St. Peter\'s Basilica. Papal Audience/Blessing.' },
      { day: 2, title: 'Italy – In the Footsteps of the Saints', desc: 'Holy Mass in Rome. Assisi – Tomb of St. Francis & St. Clare.' },
      { day: 3, title: 'Italy – In the Footsteps of the Saints', desc: 'Lanciano Eucharistic Miracle Shrine.' },
      { day: 4, title: 'Italy – In the Footsteps of the Saints', desc: 'San Giovanni Rotondo – Shrine of St. Padre Pio.' },
      { day: 5, title: 'Italy – In the Footsteps of the Saints', desc: 'Padua – Basilica of St. Anthony.' },
      { day: 6, title: 'Italy – In the Footsteps of the Saints', desc: 'Dedicated prayer, reflection, and devotional time throughout.' },
      { day: 7, title: 'France – Lourdes Pilgrimage', desc: '1 night in Monte carlo, 2 nights Lourdes. Sanctuary of Our Lady of Lourdes.' },
      { day: 8, title: 'France – Lourdes Pilgrimage', desc: 'Grotto of Massabielle. Healing Baths (where available).' },
      { day: 9, title: 'France – Lourdes Pilgrimage', desc: 'International Holy Mass. Eucharistic Procession. Evening Candlelight Rosary Procession.' },
      { day: 10, title: 'Spain – Faith & Heritage', desc: 'Barcelona • Zaragoza. Sagrada Familia Basilica.' },
      { day: 11, title: 'Spain – Faith & Heritage', desc: 'Basilica of Our Lady of the Pillar, Zaragoza.' },
      { day: 12, title: 'Spain – Faith & Heritage', desc: 'Holy Mass and devotional visits. Time for quiet prayer and pilgrimage activities.' },
      { day: 13, title: 'Portugal – Fatima', desc: '2 Nights Fatima. Sanctuary of Our Lady of Fatima. Chapel of the Apparitions.' },
      { day: 14, title: 'Portugal – Fatima', desc: 'Basilica of Our Lady of the Rosary. Holy Mass. Rosary at the Shrine.' },
      { day: 15, title: 'Portugal – Fatima', desc: 'Evening Candlelight Procession. Personal prayer and thanksgiving before departure.' }
    ]
  },
  {
    id: 'footsteps-faith',
    title: 'Footsteps of Faith: Central Europe Catholic Pilgrimage',
    category: 'Pilgrimage',
    rating: 5.0,
    reviewCount: 28,
    quote: "Spiritually Enriching • Comfortably Paced • Deeply Transformative",
    quoteAuthor: "Eutours",
    quoteMonth: "July",
    duration: 15,
    countries: ['Italy', 'Poland', 'Czech Republic', 'Slovakia', 'Austria', 'Hungary', 'Bosnia & Herzegovina'],
    destinations: 'Rome, Warsaw, Prague, Bratislava, Vienna, Budapest, Međugorje',
    ageRange: 'All Ages Welcome',
    operatedIn: 'English',
    operator: 'Eutours Premium',
    discount: 'Special Offer',
    roomType: 'Price based on Shared/Private Room',
    images: ['/images/Italy.webp', '/images/Poland.webp', '/images/Austria.webp', '/images/Hungary.webp', '/images/Germany.webp'],
    itinerary: [
      { day: 1, title: 'Italy – The Heart of Catholicism', desc: 'Rome & Vatican City • Papal Audience (subject to schedule) • St. Peter\'s Basilica • Vatican Museums' },
      { day: 2, title: 'Italy – The Heart of Catholicism', desc: 'Assisi (St. Francis) • Padua (St. Anthony)' },
      { day: 3, title: 'Italy – The Heart of Catholicism', desc: 'Lanciano Eucharistic Miracle' },
      { day: 4, title: 'Italy – The Heart of Catholicism', desc: 'San Giovanni Rotondo (St. Padre Pio)' },
      { day: 5, title: 'Italy – The Heart of Catholicism', desc: 'Continued exploration of Italy\'s sacred sites.' },
      { day: 6, title: 'Italy – The Heart of Catholicism', desc: 'Final day in Italy before departing to Poland.' },
      { day: 7, title: 'Poland', desc: 'Warsaw • Divine Mercy devotion • Pilgrimage sites associated with St. John Paul II' },
      { day: 8, title: 'Poland', desc: 'Holy Mass & reflection time' },
      { day: 9, title: 'Czech Republic', desc: 'Prague • Infant Jesus of Prague Shrine • Historic churches and spiritual heritage' },
      { day: 10, title: 'Slovakia', desc: 'Bratislava • St Martin\'s Cathedral, • Leisurely old-town pilgrimage walk' },
      { day: 11, title: 'Austria & Hungary', desc: 'Vienna: St. Stephen’s Cathedral • St. Peter’s Church • Karlskirche • Schönbrunn Palace' },
      { day: 12, title: 'Austria & Hungary', desc: 'Budapest: St. Stephen’s Basilica • Matthias Church • Gellért Hill • Castle District • Danube River' },
      { day: 13, title: 'Međugorje, Bosnia & Herzegovina', desc: 'Apparition Hill • St. James Church • Holy Mass' },
      { day: 14, title: 'Međugorje, Bosnia & Herzegovina', desc: 'Rosary & Adoration • Personal prayer, reflection, and spiritual renewal' },
      { day: 15, title: 'Drop off at airport', desc: 'Final blessings and departure to the airport.' }
    ]
  },
  {
    id: 'grand-road-adventure',
    title: 'Grand European Road Adventure',
    category: 'Road Trip',
    rating: 4.8,
    reviewCount: 56,
    quote: "From Paris boulevards to Roman streets — an unforgettable European road adventure",
    quoteAuthor: "Eutours",
    quoteMonth: "August",
    duration: 15,
    countries: ['France', 'Belgium', 'Netherlands', 'Germany', 'Switzerland', 'Italy'],
    destinations: 'Paris, Brussels, Amsterdam, Cologne, Interlaken, Venice, Pisa, Florence, Assisi, Rome',
    ageRange: 'All Ages Welcome',
    operatedIn: 'English',
    operator: 'Eutours Premium',
    discount: 'Special Offer',
    roomType: 'Price based on Shared/Private Room',
    images: ['/images/France.webp', '/images/belgium.webp', '/images/Germany.webp', '/images/Switzerland.webp', '/images/Italy.webp'],
    itinerary: [
      { day: 1, title: 'Paris, France', desc: 'Eiffel Tower photo stop, Arc de Triomphe, Louvre exterior & pyramid, Cruise tour.' },
      { day: 2, title: 'Paris Exploration', desc: 'No rushing — enjoy Paris comfortably. Café & shopping time, Paris by night experience.' },
      { day: 3, title: 'Paris → Brussels → Netherlands', desc: 'Morning Departure from Paris. Stop 1 – Brussels, Belgium. Grand Place, Atomium, Belgian waffles & chocolate.' },
      { day: 4, title: 'Amsterdam, Netherlands', desc: 'Canal district, Dam Square, Rijksmuseum area, Red Light District. Canal cruise, Tulip + Windmill area visit.' },
      { day: 5, title: 'Germany Road Experience', desc: 'Cologne Cathedral, Rhine River views, Old Town quick stop. Autobahn driving experience.' },
      { day: 6, title: 'Arrival in Interlaken, Switzerland', desc: 'Drive through Swiss Alpine roads, Lakeside highways. Interlaken Highlights: Lake Thun, Lake Brienz.' },
      { day: 7, title: 'Lauterbrunnen & Grindelwald', desc: 'Cliffside scenery, Alpine cafés, Cable car options, Lauterbrunnen Valley Waterfalls.' },
      { day: 8, title: 'Swiss Scenic Leisure Day', desc: 'Optional Experiences: Harder Kulm viewpoint, Lake cruise, Swiss chocolate shopping.' },
      { day: 9, title: 'Switzerland → Verona → Padova → Venice', desc: 'Juliet’s balcony, Roman Arena. Padova: Visit St\' Anthony\'s basilica. Evening: Venice waterfront.' },
      { day: 10, title: 'Venice → Pisa', desc: 'Scenic Italian Highway Journey. Leaning Tower of Pisa, Piazza dei Miracoli. Tuscan-style dinner & overnight stay.' },
      { day: 11, title: 'Florence → Assisi', desc: 'Florence Cathedral, Ponte Vecchio, panorama View point Florence, St Francis\'s tomb.' },
      { day: 12, title: 'Lanciano & San Giovanni Rotondo', desc: 'Eucaristico di Lanciano & Padre Pio Shrine & Church.' },
      { day: 13, title: 'Foggia → Rome', desc: 'Scenic Southern Italy Drive. Arrival in Rome. Colosseum night views, Spanish Steps area.' },
      { day: 14, title: 'Rome Exploration', desc: 'Colosseum, Roman Forum viewpoints, Vatican City, St. Peter’s Basilica, Pantheon, Piazza Navona.' },
      { day: 15, title: 'Departure', desc: 'Airport transfer.' }
    ]
  }
];

module.exports = packagesData;
